name: Setup Environment
description: Setup the environment for QA and build
runs:
  using: "composite"
  steps:
    - name: Set up task tool
      uses: arduino/setup-task@v2

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: "3.11"

    - name: Install python setuptools and wheel
      run: python -m pip install --upgrade pip setuptools pathlib wheel
      shell: bash
