services:
  # OpenTelemetry Collector, Loki, Grafana, Tempo, Prometheus
  docker-otel-lgtm:
    container_name: docker-otel-lgtm
    image: ghcr.io/grafana/docker-otel-lgtm:v0.8.4
    ports:
      - "4317:4317"   # OTLP Receiver gRPC port
      - "4318:4318"   # OTLP Receiver HTTP port
      - "3000:3000"   # Grafana
